export const organiCProductsCatalogue1 = {
  "Cereals Rice": {
    Ambemohar: "1 Kg",
    "Basmati Tukada": "1 Kg",
    Basmati: "1 Kg",
    Indrayani: "1 Kg",
  },
  Ghee: {
    Ghee: "250 ml",
  },
  Spices: {
    Halad: "200 G",
  },
  Pulses: {
    "Chana Dal": "500 G",
    Chavii: "500 G",
    Harbhara: "500 G",
    Mataki: "500 G",
    "Moong Dal": "500 G",
    Shengdana: "500 G",
    "Toor Dal": "500 G",
    "Urad Dal": "500 G",
    "Whole Moong": "500 G",
  },
  Oil: {
    "Coconut Oil": "500 ml",
    "Groundnut Oil": "1 Lt",
    "Sesame Oil": "500 ml",
    "Sunflower Oil": "1 Lt",
  },
  "Sugar Products": {
    "Jaggary Cube": "500 ml",
    "Jaggary Powder": "1 Lt",
    Jaggary: "500 ml",
    "Organic Sugar": "1 Lt",
  },
};

export const organiCProductsCatalogue2 = {
  "Cereals Rice": {
    "Basmati Rice Premium": "1kg",
    "Biryani Basmati Rice": "1kg",
    "Brown Rice Premium": "1kg",
    "Sona Mansoori Rice": "1kg",
  },
  Cereals: {
    "Bajra Flour": "500 Gm",
    "Bajra Whole": "1 Kg",
    "Jowar Whole": "1 Kg",
    Amaranthus: "500 Gm",
    Quinoa: "500 Gm",
    "Barley Flour": "500 Gm",
    "Maize Dalia": "300 Gm",
    "Multigrain Flour": "750 Gm",
    "Pearl Barley": "500 Gm",
    "Red Rice Poha": "500 Gm",
    "Rice Murmure": "200 Gm",
    "Rice Poha": "500 Gm",
    "Wheat Bran": "400 Gm",
    "Wheat Dalia (Porridge)": "500 Gm",
    "Wheat Maida": "500 Gm",
    "Wheat Suji": "500 Gm",
    "Whole Wheat Flour": "5 Kg",
    "Amaranthus Flour": "500 Gm",
    "Buckwheat Flour": "500 Gm",
    "Maize Flour": "500 Gm",
    "Ragi Flour": "500 Gm",
    "Rice Flour": "500 Gm",
    "Shorgum Flour": "500 Gm",
    "Soybean Flour": "300 Gm",
  },
  "Roasted Snacks": {
    "Chana Jor (Flakes)": "150 Gm",
    "MoongJor (Flakes)": "150 Gm",
    "Puffed Wheat": "150 Gm",
    "Multi Grains Mix": "150 Gm",
  },
  "Nuts and Dry Fruits": {
    Almonds: "250 Gm",
    Cashew: "200 Gm",
    Raisins: "250 Gm",
    Walnut: "150 Gm",
  },
  "Healthy Foods": {
    "Aloevera Juice": "500 Ml",
    "Amchur Powder": "100 Gm",
    "Amla Powder": "100 Gm",
    "Awh Juice": "500 Ml",
    Honey: "250 Gm",
    "Jamun Juice": "500 Ml",
    "Moringa Powder": "100 Gm",
    "Triphala Juice": "500 Ml",
    "Triphala Powder": "100 Gm",
    "Wheat Grass Powder": "100 Gm",
  },
  Millets: {
    "Foxtail Millet": "300 Gm",
    "Kodo Millet": "500 Gm",
  },
  Pulses: {
    "Arhar Dal": "1 Kg",
    "Chana Dal": "300 Gm",
    "Chana Whole": "300 Gm",
    "Cowpea Black Eye": "500 Gm",
    "Cowpea Red": "500 Gm",
    "Green Dry Peas": "500 Gm",
    "Kabuli Chana": "500 Gm",
    "Masur split Washed": "500 Gm",
    "Masur Whole": "500 Gm",
    "Moong split": "500 Gm",
    "Moong split Washed": "300 Gm",
    "Moong Whole": "500 Gm",
    "Moth Whole": "500 Gm",
    "Panchrangi Dal": "1 Kg",
    Peanuts: "500 Gm",
    "Ragi Whole": "1 Kg",
    "Rajma Chitra": "500 Gm",
    "Rajma Red": "500 Gm",
    "Soybean Whole": "300 Gm",
    "Urad split": "1 Kg",
    "Urad Washed split": "500 Gm",
    "Urad Whole": "500 Gm",
    "White Peas": "500 Gm",
  },
  "Pulses Based": {
    "Chana Besan": "500 Gm",
    "Roasted Chana Dal": "500 Gm",
  },
  "Indian Beverages": {
    "CTC Tea": "250 Gm",
    "Green Tea": "200 Gm",
  },
  Savories: {
    "Amla Candy Chatpat": "250 Gm",
    "Amla Candy Sweet": "250 Gm",
    "Bei candy": "250 Gm",
  },
  "Processed Products": {
    "Flaxseed Raw": "150 Gm",
    "Roasted Flaxseed": "100 Gm",
    "Sugarcane Vinegar": "200 Ml",
  },
  "Processed Products Pasta": {
    "Pasta Fusilli ": "250 Gm",
    "Pasta Macroni ": "250 Gm",
    "Pasta Penne ": "230 Gm",
  },
  "Processed Products Flakes": {
    "Corn Flakes ": "200 Gm",
    "Oat Flakes ": "250 Gm",
    "Wheat Flakes ": "250 Gm",
  },
  Oil: {
    "Coconut Oil": "400 Ml",
    "Groundnut Oil": "1 Ltr",
    "Mustard Oil": "1 Ltr",
    "Sesame Oil": "1 Ltr",
    "Sunflower Oil": "1 Ltr",
    "White Sesame Oil": "1 Ltr",
  },
  "Sugar Products": {
    "Brown Sugar": "1kg",
    Sugar: "1kg",
  },
  Ghee: {
    "A2 cow Ghee": "350 Ml",
    "Bay Leaves": "50 Gm",
    "Premium Cow Ghee": "400 Ml",
  },
  Spices: {
    "Ajwain (Carom Seeds)": "100 Gm",
    "Black Pepper": "40 Gm",
    "Cinnamon Powder": "100 Gm",
    "Cinnamon Sticks": "75 Gm",
    Clove: "75 Gm",
    "Coriander Powder": "100 Gm",
    "Coriander Whole": "200 Gm",
    "Cumin Whole": "100 Gm",
    "Fennel (Saunf)": "100 Gm",
    Fenugreek: "150 Gm",
    "Garam Masala Powder": "100 Gm",
    "Green Cardamom": "75 Gm",
    "Heeng Powder": "50 Gm",
    "Himalayan Pink Rock Salt": "1 Kg",
    "Kasuri Methi": "30 Gm",
    "Mustard Black": "130 Gm",
    "Mustard Yellow": "150 Gm",
    Rai: "150 Gm",
    "Red Chilli Powder": "100 Gm",
    "Red Chilli Whole": "50 Gm",
    "Turmeric Powder": "100 Gm",
  },
  "Processed Products Jam": {
    "Apple Jam": "230 Gm",
    "Mango Jam": "250 Gm",
    "Mix Fruit Jam": "250 Gm",
    "Pineapple Jam": "250 Gm",
  },
  "Processed Products Pickle": {
    "Chilli Pickle": "350 Gm",
    "Lemon Pickle": "350 Gm",
    "Mango Pickle": "350 Gm",
  },
};
